services:
  mongodb:
    image: mongo:7.0
    container_name: usbcomedor-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: usbcomedor
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    external: false